version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoose
      MONGO_INITDB_ROOT_PASSWORD: mongoose
      MONGO_INITDB_DATABASE: mongoose
    volumes:
    - ./datadir:/data/db
  api:
    image: api:latest
    build:
      context: ./backend
    container_name: api
    depends_on:
    - "mongodb"
    ports:
    - 8081:8080
    environment:
      MONGO_URI: mongodb://mongoose:mongoose@mongodb:27017/mongoose?authSource=admin
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    container_name: frontend
    ports:
    - 80:3000
    depends_on:
    - "api"

